TASK: "det"
MODEL:
  NAME: "ssd"
  THRESHOLD: 0.5
  NEG_POS_RATIO: 3
  CENTER_VARIANCE: 0.1
  SIZE_VARIANCE: 0.2
  BACKBONE:
    NAME: 'vgg'
    OUT_CHANNELS: (512, 1024, 512, 256, 256, 256)
    PRETRAINED: True
  PRIORS:
    FEATURE_MAPS: [38, 19, 10, 5, 3, 1]
    STRIDES: [8, 16, 32, 64, 100, 300]
    MIN_SIZES: [30, 60, 111, 162, 213, 264]
    MAX_SIZES: [60, 111, 162, 213, 264, 315]
    ASPECT_RATIOS: [[2], [2, 3], [2, 3], [2, 3], [2], [2]]
    BOXES_PER_LOCATION: [4, 6, 6, 6, 4, 4]  # number of boxes per feature map location
    CLIP: True

INPUT:
    DIMS: (300, 300)

SOLVER:
  CHECKPOINT_PERIOD: 2500
  OPTIMIZER:
    NAME: "adam"
  SCHEDULER:
    NAME: "WarmupMultiStepLR"

CHECKPOINTER:
  DIR: "log/psp_voc"

DATASET:
  NAME: 'voc'
  TRAIN: ("voc_2012_trainval", "voc_2007_trainval")
  TEST: ("voc_2007_test",)
  NUM_CLASS: 21
  DATA_TYPE: ['bbox']

TRANSFORM:
  TRAIN:
    - name: RandRotate
      args:
        rotate: [-10, 10]
        padding: [0, 0, 0]
        ignore_label: 255

    - name: RandomGaussianBlur
    - name: RandomHorizontalFlip
    - name: ColorJitter
      args:
        brightness: 0.2
        contrast: 0.2
        saturation: 0.5
        hue: 0.2

    - name: Expand
      args:
        mean: [123.675, 116.28, 103.53]

    - name: RandomSampleCrop
      args:
        is_remove_empty: False

    - name: Resize
      args:
        a: 300
        b: 300
        mode: 'wh'
    - name: ToTensor
    - name: Normalize
      args:
        mean: [123.675, 116.28, 103.53]
#        std: [58.395, 57.120, 57.375]

  VAL:
    - name: PaddingAndResize
      args:
        size: [300, 300]
        padding: [0, 0, 0]
        ignore_label: 255

    - name: ToTensor
    - name: Normalize
      args:
        mean: [123.675, 116.28, 103.53]
#        std: [58.395, 57.120, 57.375]
